import type { Metadata } from 'next'
import { LegalPageLayout } from '@/components/legal/legal-page-layout'

export const metadata: Metadata = {
  title: 'Terms of Service — Murphy',
  description:
    'Terms and conditions for using Murphy, the AI phone concierge by Cardinal Conseils.',
}

const LAST_UPDATED = 'March 17, 2026'

const TOC_SECTIONS = [
  { id: 'overview', label: 'About Murphy' },
  { id: 'ai-disclosure', label: 'AI Disclosure (CA SB-1001)' },
  { id: 'eligibility', label: 'Eligibility' },
  { id: 'service-description', label: 'How the Service Works' },
  { id: 'acceptable-use', label: 'Acceptable Use' },
  { id: 'third-party', label: 'Third-Party Services' },
  { id: 'disclaimers', label: 'Disclaimers' },
  { id: 'liability', label: 'Limitation of Liability' },
  { id: 'changes', label: 'Changes to Terms' },
  { id: 'contact', label: 'Contact Us' },
]

export default function TermsPage() {
  return (
    <LegalPageLayout
      sections={TOC_SECTIONS}
      title="Terms of Service"
      lastUpdated={LAST_UPDATED}
    >
      {/* About Murphy */}
      <section id="overview">
        <h2 className="font-display font-bold text-2xl text-foreground mt-10 mb-4" id="overview">
          About Murphy
        </h2>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          Cardinal Conseils ("we", "us", "our", "Cardinal Conseils") operates Murphy, an
          AI-powered phone concierge service. Murphy allows users to call a dedicated phone number,
          describe a service they need (such as a plumber, electrician, or cleaner), and have the
          AI agent find a local provider, call them to check availability, and connect the caller
          live to a willing provider.
        </p>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          These Terms of Service ("Terms") govern your access to and use of the Murphy service,
          including the murphy.help website and the Murphy phone service. By using Murphy, you
          agree to be bound by these Terms. If you do not agree to these Terms, do not use the
          service.
        </p>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          For questions about these Terms, contact us at{' '}
          <a href="mailto:info@cardinalconseils.com" className="text-primary hover:underline">
            info@cardinalconseils.com
          </a>
          .
        </p>
      </section>

      {/* AI Disclosure — CA SB-1001 */}
      <section id="ai-disclosure">
        <h2 className="font-display font-bold text-2xl text-foreground mt-10 mb-4" id="ai-disclosure">
          AI Disclosure (CA SB-1001)
        </h2>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          <strong>Murphy is an artificial intelligence agent, not a human operator.</strong> By
          using this service, you acknowledge and accept that:
        </p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Murphy is powered by AI language models. All greetings, questions, and responses you
            hear during a Murphy call are generated by an AI system.
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Murphy makes automated telephone calls to service providers on your behalf. These are
            AI-to-human calls, not human-to-human calls.
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            In compliance with California SB-1001, Murphy identifies itself as an AI agent to all
            parties it contacts. Murphy&apos;s first utterance when a service provider answers is an
            explicit AI identity disclosure.
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Murphy does not attempt to deceive any person into believing they are communicating
            with a human. Murphy will not deny being an AI when sincerely asked.
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Murphy&apos;s automated calling practices are consistent with FCC regulations regarding
            automated telephone dialing systems (ATDS) and pre-recorded voice messages under TCPA.
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            AI-generated responses may contain errors or inaccuracies. Murphy does not guarantee
            that provider information, availability, pricing, or service descriptions are accurate
            or up to date.
          </li>
        </ul>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          If you do not wish to interact with an AI agent or have an AI agent make calls on your
          behalf, do not use the Murphy service.
        </p>
      </section>

      {/* Eligibility */}
      <section id="eligibility">
        <h2 className="font-display font-bold text-2xl text-foreground mt-10 mb-4" id="eligibility">
          Eligibility
        </h2>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          You must be at least <strong>18 years of age</strong> to use the Murphy service. By
          using Murphy, you represent and warrant that you are 18 or older and have the legal
          capacity to enter into these Terms.
        </p>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          The Murphy service is currently available for use in the <strong>United States</strong>{' '}
          and <strong>Canada</strong>. Use from other jurisdictions may be subject to additional
          restrictions or unavailability.
        </p>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          If you are using Murphy on behalf of a business or organization, you represent that you
          have authority to bind that organization to these Terms.
        </p>
      </section>

      {/* How the Service Works */}
      <section id="service-description">
        <h2 className="font-display font-bold text-2xl text-foreground mt-10 mb-4" id="service-description">
          How the Service Works
        </h2>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          Murphy operates as follows:
        </p>
        <ol className="list-decimal pl-6 space-y-2 mb-4">
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            <strong>You call Murphy</strong> — dial the Murphy phone number to initiate a service-matching session
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            <strong>AI greets and captures your request</strong> — Murphy&apos;s AI agent greets you, asks your name, and captures your service need through natural conversation
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            <strong>SMS consent</strong> — Murphy asks if you consent to receive an SMS recap at the end of the call (optional, under TCPA)
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            <strong>Provider search</strong> — Murphy searches Google Places and other sources for local providers matching your request and location
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            <strong>Outbound calls to providers</strong> — Murphy calls providers sequentially, disclosing its AI identity, checking availability, and asking if they can take your job
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            <strong>Live transfer</strong> — when a willing provider is found, Murphy performs a warm transfer, connecting you live to the provider
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            <strong>SMS recap</strong> — if you consented, you receive a text message with the provider&apos;s contact information and an optional tip link
          </li>
        </ol>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          Murphy does not schedule, book, negotiate prices, or enter into contracts on your behalf.
          Murphy&apos;s role ends at the point of connection — any service agreement is between you and
          the provider directly.
        </p>
      </section>

      {/* Acceptable Use */}
      <section id="acceptable-use">
        <h2 className="font-display font-bold text-2xl text-foreground mt-10 mb-4" id="acceptable-use">
          Acceptable Use
        </h2>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          You agree to use Murphy only for lawful purposes and in accordance with these Terms. You
          must not:
        </p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Submit fraudulent or fictitious service requests, or use Murphy with no intent of
            engaging a provider
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Abuse the outbound calling system to harass, spam, or repeatedly contact providers
            without a genuine service need
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Misrepresent your identity, location, or service needs to Murphy or to providers
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Use Murphy to engage in any illegal activity, including fraud, harassment, or
            circumventing TCPA or other telecommunications regulations
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Attempt to reverse-engineer, scrape, or exploit the Murphy service or its AI systems
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Interfere with or disrupt the Murphy service or its infrastructure
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Use Murphy for any purpose that violates the rights of third parties, including service
            providers contacted on your behalf
          </li>
        </ul>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          We reserve the right to suspend or terminate access to Murphy for any user who violates
          these acceptable use requirements.
        </p>
      </section>

      {/* Third-Party Services */}
      <section id="third-party">
        <h2 className="font-display font-bold text-2xl text-foreground mt-10 mb-4" id="third-party">
          Third-Party Services
        </h2>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          Murphy connects users with independent third-party service providers (plumbers,
          electricians, cleaners, etc.). Cardinal Conseils is not an employer, agent, or partner
          of any provider. We do not:
        </p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Employ, vet, license, or background-check service providers
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Guarantee the quality, safety, pricing, or availability of any provider
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Endorse or recommend any specific provider
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Accept responsibility for the acts or omissions of any provider
          </li>
        </ul>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          Provider listings are sourced from Google Places, which is subject to{' '}
          <a
            href="https://policies.google.com/terms"
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary hover:underline"
          >
            Google&apos;s Terms of Service
          </a>
          . The accuracy and completeness of provider data is not guaranteed.
        </p>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          BuyMeACoffee tip links included in SMS recaps are entirely voluntary. Tips are processed
          by BuyMeACoffee Inc. under their own terms. Cardinal Conseils receives any tips sent
          through these links.
        </p>
      </section>

      {/* Disclaimers */}
      <section id="disclaimers">
        <h2 className="font-display font-bold text-2xl text-foreground mt-10 mb-4" id="disclaimers">
          Disclaimers
        </h2>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          THE MURPHY SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY
          KIND, EXPRESS OR IMPLIED. TO THE MAXIMUM EXTENT PERMITTED BY LAW, CARDINAL CONSEILS
          DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO:
        </p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Warranties of merchantability, fitness for a particular purpose, and non-infringement
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Any warranty that the service will be uninterrupted, error-free, or free of viruses or
            other harmful components
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Any warranty regarding the accuracy or reliability of AI-generated responses or
            provider information
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Any warranty that a service provider will be found, available, or suitable for your
            needs
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Any warranty that Murphy will successfully complete a transfer or that a provider will
            accept your request
          </li>
        </ul>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          AI responses may contain errors, omissions, or inaccuracies. You should independently
          verify any provider information before engaging their services.
        </p>
      </section>

      {/* Limitation of Liability */}
      <section id="liability">
        <h2 className="font-display font-bold text-2xl text-foreground mt-10 mb-4" id="liability">
          Limitation of Liability
        </h2>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL CARDINAL CONSEILS,
          ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
          SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO:
        </p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Loss of profits, revenue, data, or business opportunities
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Damages resulting from your reliance on AI-generated information
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Damages resulting from the acts or omissions of any third-party service provider
            connected through Murphy
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Damages resulting from unauthorized access to or alteration of your data
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Any other indirect or consequential loss arising from your use of or inability to use
            the service
          </li>
        </ul>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          IN NO EVENT SHALL CARDINAL CONSEILS&apos; TOTAL LIABILITY TO YOU FOR ALL CLAIMS EXCEED THE
          AMOUNTS PAID BY YOU TO CARDINAL CONSEILS IN THE 12 MONTHS PRECEDING THE CLAIM. AS THE
          MURPHY SERVICE IS CURRENTLY FREE TO USE, THIS EFFECTIVELY LIMITS OUR LIABILITY TO ZERO
          DOLLARS, TO THE EXTENT PERMITTED BY LAW.
        </p>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          Some jurisdictions do not allow the exclusion of certain warranties or limitation of
          liability for certain types of damages. In such jurisdictions, our liability is limited to
          the greatest extent permitted by law.
        </p>
      </section>

      {/* Changes to Terms */}
      <section id="changes">
        <h2 className="font-display font-bold text-2xl text-foreground mt-10 mb-4" id="changes">
          Changes to Terms
        </h2>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          Cardinal Conseils reserves the right to modify these Terms of Service at any time. When
          we make material changes, we will:
        </p>
        <ul className="list-disc pl-6 space-y-2 mb-4">
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Post the updated Terms on this page with a revised &quot;Last updated&quot; date
          </li>
          <li className="font-sans text-sm leading-7 text-muted-foreground">
            Notify registered users by email where required by applicable law
          </li>
        </ul>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          Your continued use of Murphy after any changes to these Terms constitutes your acceptance
          of the revised Terms. If you do not agree to the revised Terms, you must stop using the
          service.
        </p>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          These Terms are governed by the laws of the Province of Quebec, Canada, without regard to
          conflict of law principles. Any dispute arising from these Terms shall be resolved in the
          courts of competent jurisdiction in Quebec.
        </p>
      </section>

      {/* Contact Us */}
      <section id="contact">
        <h2 className="font-display font-bold text-2xl text-foreground mt-10 mb-4" id="contact">
          Contact Us
        </h2>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          If you have questions about these Terms of Service, please contact:
        </p>
        <p className="font-sans text-sm leading-7 text-muted-foreground mb-4">
          <strong>Cardinal Conseils</strong>
          <br />
          Legal Inquiries
          <br />
          <a href="mailto:info@cardinalconseils.com" className="text-primary hover:underline">
            info@cardinalconseils.com
          </a>
        </p>
      </section>
    </LegalPageLayout>
  )
}
